title: Heitor Gouvêa
description: ""
keywords: Heitor Gouvêa, Security Researcher, Independent, Vulnerability, Pentester, Bug Bounty Hunter, Perl, Fuzzing, Nipe, Nozaki, Spellbook
author: Heitor Gouvêa
baseurl: "" 
url: "https://heitorgouvea.me" 

twitter_username: htrgouvea
github_username:  htrgouvea
donate: donate

include: [_pages]
exclude: ["README.md", "SECURITY.md", "LICENSE.md", "Gemfile", "Dockerfile"]

markdown: kramdown
permalink: /:year/:month/:day/:title

sass:
    style: compressed
plugins:
  - jemoji
  - jekyll-sitemap

google_analytics: G-VHN1CKT5Q3